device: 'cuda'

model_path: '/BS/nshvetso/work/cache/huggingface/transformers/models--vicuna-13b'
data_path: 'data/howto100m_sentencified/sentencified_htm_10k_with_audio.pickle'
word_blocks: 200

prompt: "Rephrase the following first-person speech into a detailed third-person description with one action per sentence: \"{}\""
examples: []

model_generate_args:
#  temperature: 0.7
#  do_sample: true
  max_length: 2048
  eos_token_id: 2277

batch_processing: true
batch_size: 8

save_dir: 'output/vicuna'