device: 'cuda'

model_path: '/BS/nshvetso/work/cache/huggingface/transformers/models--vicuna-13b'
data_path: 'data/howto100m_sentencified/sentencified_htm_10k_with_audio.pickle'
word_blocks: 200

prompt: "Here is an automatically recognized speech (ASR) from a YouTube video: \"{}\". Write synopses for this video. Keep only actions that happen in the present time, do not include what the person is saying."
examples: []

model_generate_args:
  temperature: 0.7
  do_sample: true
  max_length: 2048
  eos_token_id: 2277

batch_processing: true
batch_size: 8

save_dir: 'output/vicuna'