device: 'cuda'

model_path: '/BS/nshvetso/work/cache/huggingface/transformers/models--vicuna-13b'
data_path: 'data/howto100m_sentencified/sentencified_htm_100k_with_audio.pickle'
word_blocks: '200w_with_ts'

prompt: "Here is an automatically recognized speech (ASR) from a YouTube video with timestamps: \"{}\". Write a synopsis for this video. Write only short sentences. Describe only one action per sentence.  Keep only actions that happen in the present time. Begin each sentence with estimated timestamp."
examples: []

model_generate_args:
  temperature: 0.7
  do_sample: true
  max_length: 2048
  eos_token_id: 2277

batch_processing: true
batch_size: 6

save_dir: 'output/vicuna'